# Generated by Django 3.0 on 2020-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_carousel', models.ImageField(upload_to='images/')),
                ('título_no_site', models.CharField(blank=True, max_length=255)),
                ('sub_titulo_no_site', models.CharField(blank=True, max_length=255)),
                ('nome_imagem', models.CharField(default='Nome da sua imagem aqui', help_text='<h3><strong>AVISO: </strong> Copia o nome da sua imagem e cole-o aqui sem extensão!!!</h3>', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='<p><strong>AVISO: </strong> Se você não quiser que esta imagem apareça no banner, DESMARQUE este campo!</p>')),
                ('atualizada', models.DateTimeField(auto_now=True)),
                ('data_hora_criação', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Imagens de destaque',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Curso', models.CharField(choices=[('TÉCNICO EM INFORMÁTICA', 'TÉCNICO EM INFORMÁTICA'), ('TÉCNICO EM AGROPECUÁRIA', 'TÉCNICO EM EM AGROPECUÁRIA'), ('TÉCNICO EM ELETROMECÂNICA', 'TÉCNICO EM ELETROMECÂNICA'), ('TÉCNICO EM FINANÇAS', 'TÉCNICO EM FINANÇAS')], max_length=30)),
                ('data_Inicio', models.DateField()),
                ('num_Alunos', models.IntegerField()),
                ('num_Prof', models.IntegerField()),
                ('alunos_Formados', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Evento', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título_notícia', models.CharField(default='Título da notícia *', max_length=255)),
                ('image_notícia', models.ImageField(upload_to='images/')),
                ('sub_titulo_noticia', models.CharField(blank=True, default='Subtítulo da notícia', max_length=255)),
                ('noticia', models.TextField(default='Escreva a sua notícia aqui *')),
                ('ativa', models.BooleanField(default=True, help_text='<p>Se você não quiser que esta notícia apareça no site, DESMARQUE este campo!</p>')),
                ('atualizada', models.DateTimeField(auto_now=True)),
                ('data_hora_criação', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(default='Nome do projeto *', max_length=255)),
                ('logotipo_projeto', models.ImageField(upload_to='images/')),
                ('slogan_projeto', models.CharField(blank=True, default='Slogan do projeto', max_length=255)),
                ('descricao', models.TextField(default='Descrição do projeto entra aqui * ')),
                ('ativo', models.BooleanField(default=True, help_text='<p>Se você não quiser que este projeto seja visualizado no site, DESMARQUE este campo!</p>')),
                ('atualizar', models.DateTimeField(auto_now=True)),
                ('data_hora_criação', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Título *', max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('texto_correspondente', models.TextField(default='Escreva o seu texto aqui *')),
                ('ativo', models.BooleanField(default=True, help_text='<p>Se você não quiser que este item apareça no site, DESMARQUE este campo!</p>')),
                ('atualizar', models.DateTimeField(auto_now=True)),
                ('data_hora_criação', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Prof', models.CharField(max_length=100)),
                ('formacao', models.CharField(default='Eng. Computação', max_length=100)),
                ('titulo_Academico', models.CharField(choices=[('BACHAREL', 'Bacharel'), ('ESPECIALISATA', 'Especialista'), ('MESTRE', 'Mestre'), ('PHD', 'PhD')], max_length=30)),
                ('ano_Inicio', models.CharField(max_length=4)),
                ('turmas', models.IntegerField()),
                ('membro_Organizacao', models.BooleanField(default=True)),
                ('curso_Leciona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saada_ong.Cursos')),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=3)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=30)),
                ('idade', models.IntegerField()),
                ('eh_destaque', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saada_ong.Cursos')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
