# Generated by Django 3.0 on 2020-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saada_ong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='nome_imagem',
            field=models.CharField(default='Nome da sua imagem aqui', help_text='<p><strong>AVISO: </strong> Copia o nome da sua imagem e cole-o aqui sem extensão!!!</p>', max_length=255),
        ),
    ]
