# Generated by Django 3.0 on 2020-05-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saada_ong', '0002_auto_20200510_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='image_notícia',
            field=models.ImageField(upload_to='images/news/'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='logotipo_projeto',
            field=models.ImageField(upload_to='images/projects/'),
        ),
    ]
